#!/bin/sh
# ~/.config/shell/aliasrc
#
#    >=>                            >=>     >=>
#    >=>                        >>  >=>     >=>
#    >=>   >==>    >=>     >=>      >=>     >=>   >==>    >=>     >=>
#  >=>>=> >>   >=>   >=>   >=>  >=>  >=>  >=>>=> >>   >=>   >=>   >=>
# >>  >=> >>===>>=>   >=> >=>   >=>  >=> >>  >=> >>===>>=>   >=> >=>
# >>  >=> >>           >=>=>    >=>  >=> >>  >=> >>           >=>=>
#  >=>>=>  >====>       >=>     >=> >==>  >=>>=>  >====>       >=>
#

# bat enhancement
alias bat='bat --style header --style rules --style snip --style changes --style header'

# Changing "ls" to "exa"
alias ll='exa -GlF -s name --icons --no-user --no-time --group-directories-first --color-scale  -@'
alias la='ll -as "size" '
alias l.="ls -a | egrep '^\.'"
alias ls="ls --color=auto"

# Directory Traversal
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias v='$EDITOR'

# confirm before overwriting something
alias cp="cp -rv"
alias mv='mv -v'
alias rm='rm -vI'
alias bc="bc -ql"
alias mkd="mkdir -pv"
alias ffmpeg="ffmpeg -hide_banner"
# alias mpv="devour mpv"
alias lf="lfub"

# adding flags
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# Python alias
alias py='python3'

# Xdg-open alias
alias open='xdg-open'

# youtube-dl alias
alias ytb="youtube-dl -f bestvideo+bestaudio -o '%(title)s.%(ext)s' --external-downloader=aria2c"
alias yta="youtube-dl -x -f bestaudio -o '%(title)s.%(ext)s' --external-downloader=aria2c"
alias ytdl="youtube-dl -f best -o '%(title)s.%(ext)s' --external-downloader=aria2c"
alias ytpdl="youtube-dl -f best -o '%(playlist_index)s. %(title)s.%(ext)s' --external-downloader=aria2c" 

# Dotfile management
alias dots='/usr/bin/git --git-dir=$HOME/proj/dotfiles/ --work-tree=$HOME'

# useful alais
alias hst="history | cut -c 8- | sort | uniq | fzf | tr '\\n' ' ' | xclip -sel c"
alias wget="wget --hsts-file=/home/devildev/.cache/wget-hsts"
alias se="du -a $XDG_BINARY_HOME | cut -f2 | fzf --multi | xargs -r $EDITOR"
alias update="paru -Syu;kill -35 $(cat ~/.cache/pidofbar)"

# Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq) 2>/dev/null'
alias syncmob='rsync -rtvP -zz --delete ~/proj/notes/* mobile:~/SDCard/notes'

alias pomo="pomo --path /home/devildev/.config/pomo/config.json"
[ ! -x /usr/bin/yay ] && [ -x /usr/bin/paru ] && alias yay='paru'
[ ! -x /usr/bin/sxiv ] && [ -x /usr/bin/nsxiv ] && alias sxiv='nsxiv'
# vim:ft=sh
