#!/bin/sh
# shellcheck disable=SC2155 

# export ENV=$HOME/.config/shell/dash
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"
export LANG=en_US.UTF-8

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BINARY_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/.cache"

export XAUTHORITY=/tmp/Xauthority
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export LESSHISTFILE="$XDG_CACHE_HOME/lesshst"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export PYTHONHISTORY="$XDG_CACHE_HOME/python_history"
export PYDORO_CONFIG_FILE="$XDG_CONFIG_HOME/pydoro/pydoro.ini"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export DIANA_SECRET_TOKEN="HTSnxdNZ5fJ3qQ+4cHE9y0zFJtpw34PMt0+QyBm/Sz0="
export _Z_DATA="$XDG_DATA_HOME/z"

# For other applications
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

mkdir -p "$XDG_BINARY_HOME"
export PATH="$PATH":"$XDG_BINARY_HOME"

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
 exec startx "$XINITRC"
fi
