#!/bin/sh

# ~/.config/x11/xinitrc
#
#    >=>                            >=>     >=>
#    >=>                        >>  >=>     >=>
#    >=>   >==>    >=>     >=>      >=>     >=>   >==>    >=>     >=>
#  >=>>=> >>   >=>   >=>   >=>  >=>  >=>  >=>>=> >>   >=>   >=>   >=>
# >>  >=> >>===>>=>   >=> >=>   >=>  >=> >>  >=> >>===>>=>   >=> >=>
# >>  >=> >>           >=>=>    >=>  >=> >>  >=> >>           >=>=>
#  >=>>=>  >====>       >=>     >=> >==>  >=>>=>  >====>       >=>
#

set_wallpaper -r &
~/.config/dwm/./bar.sh &
xrandr -s 1920x1080
xset r rate 300 50 &
xrdb -load ~/.config/x11/xresources &
xcompmgr &
sxhkd &
mpd &
dunst &
unclutter &
exec dwm > /dev/null 2>&1
